### ISSUE TITLE
Feature: Tooltips should align on -> 

### ISSUE THREAD

**Issue by rojepp** [fsharp/xamarin-monodevelop-fsharp-addin#11]
Minor 
![screenshot 2015-05-09 23 49 54](https://cloud.githubusercontent.com/assets/445888/7552168/210502a4-f6a6-11e4-9eb9-603d09be02a5.png)

minor, but would be nice if it said
```fsharp
   val toBePartiallyApplied :
      datNumba  : int    ->
      thaString : string -> 
      be        : bool 
               -> unit
```

**Comment by 7sharp9** [comment]
The alignment was on purpose so the types were vertically aligned.

**Comment by rojepp** [comment]
Yes, that is great. I was merely suggesting that it might look better if the `->` were *also* aligned. Not very important. These tooltips are already miles better than any other editor. :)

**Comment by 7sharp9** [comment]
We could do if there was two spaces after the colons.

**Comment by 7sharp9** [comment]
`->` aligned
![screen shot 2015-05-12 at 08 39 19](https://cloud.githubusercontent.com/assets/588746/7582104/6be9cf4c-f882-11e4-93b0-c3b9e69a5bb7.png)

**Comment by 7sharp9** [comment]
Oops I just realised this is slightly different to what you actually asked for!

**Comment by rojepp** [comment]
How does it look with the `toBePartiallyApplied` function?

**Comment by 7sharp9** [comment]
Ignore me I was looking at the wrong part, formatting the right hand `->` is more fiddly than it looks.  Ill leave this for now.

**Comment by 7sharp9** [comment]
Closing, moved to bugzilla: https://bugzilla.xamarin.com/show_bug.cgi?id=33098
