### ISSUE TITLE
Xamarin Studio on Windows ignores F# compiler path

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/xamarin-monodevelop-fsharp-addin#23]
_From @buybackoff on July 16, 2014 14:56_

I have installed Scala and Xamarin Studio started to use fsc from Scala distribution to compile F# projects when I uncheck "Use MsBuild" box in project settings. 

When I uncheck "Use default" in Options -> F# Settings -> F# Default Compiler nothing happens. (I reopened Xamarin Studio several times).

Where the default path is stored?

_Copied from original issue: fsharp/fsharpbinding#667_

**Comment by 7sharp9** [comment]
_From @knocte on July 16, 2014 14:58_

I guess fsharpbinding should use 'fsharpc', not 'fsc'.

**Comment by 7sharp9** [comment]
_From @buybackoff on July 16, 2014 15:2_

More details:
To resolve the issue I renamed `scala/bin/fsc` to `fsc_` and re-run Mono build, then I renamed `scala/bin/fsc_` back to `fsc`. It works now.

Obviously there is some run-time resolution of fsc location, and that location is cached somewhere.

The issue is that the setting  `Options -> F# Settings -> F# Default Compiler -> Path` is ingnored.

**Comment by 7sharp9** [comment]
_From @buybackoff on July 16, 2014 15:10_

Even more details: after renaming scala/fsc the option started working, but default location always chooses Scala's fsc when I check the box "use default".

Some irregular behavior... But with the workaround above the issue could be closed, just FYI

**Comment by knocte** [comment]
But where in the code is the assumption that `fsc` means fsharpcompiler? Thats the wrong thing. BTW, why is this issue closed?

**Comment by knocte** [comment]
Oh sorry, it's not closed, I confused the UI.

**Comment by 7sharp9** [comment]
@knocte This bit makes the assumption: https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/blob/master/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs#L286

via tryfind here: https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/blob/master/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs#L205 which returns the first

**Comment by knocte** [comment]
Ok, so it's a matter of removing that pattern-matching block?

**Comment by 7sharp9** [comment]
The solution would be to use findAll and filter out anything not relating to F# before making a selection I think.

**Comment by knocte** [comment]
Why? `fsc` should simply not be looked for (except the full form `fsc.exe`)

**Comment by 7sharp9** [comment]
To be honest I only quickly glanced at the code, the solution is to just stop scala being used if its also installed.

**Comment by knocte** [comment]
Looking for scala seems mental to me. Development environments should not be aware of other development environments.

**Comment by 7sharp9** [comment]
If you path contains scala and F# then there will be two fsc.exe present with different parents.

**Comment by knocte** [comment]
Oh I see, I wasn't thinking about scala's fsc.exe sorry.

Shouldn't we try to make this a fix in F# upstream repo to make the .exe be renamed to fsharpc.exe?

**Comment by 7sharp9** [comment]
Closing, moved to bugzilla: https://bugzilla.xamarin.com/show_bug.cgi?id=33094
